<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 barn.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/barn-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.SM_Bld_Barn_01001.geometry}
      material={gltf.materials['Farm3.008']}
      position={[-31.62, -0.3, -6.34]}
      rotation={[0, -1.57, 0]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Barn_01_Door_01001.geometry}
        material={gltf.materials['Farm3.008']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Barn_01_Door_02001.geometry}
        material={gltf.materials['Farm3.008']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Barn_01_Door_03001.geometry}
        material={gltf.materials['Farm3.008']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Barn_01_Door_04001.geometry}
        material={gltf.materials['Farm3.008']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Barn_01_Shutter_01001.geometry}
        material={gltf.materials['Farm3.008']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Barn_01_Shutter_02001.geometry}
        material={gltf.materials['Farm3.008']}
      />
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
