<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 dancingchili.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/dancingchili-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions['testClip']?.play()
  $: $actions['PerfectChili.blink']?.play()
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="TEST">
      <T.Group name="Mixamo_RIG">
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="PerfectChili030"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili030.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          skeleton={gltf.nodes.PerfectChili030.skeleton}
          morphTargetDictionary={gltf.nodes.PerfectChili030.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.PerfectChili030.morphTargetInfluences}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
