<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 drivingchili.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/drivingchili-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions['TractorShake']?.play()
  $: $actions['TractorAnim']?.play()
  $: $actions['BLTireRot']?.play()
  $: $actions['BRTireRot']?.play()
  $: $actions['FLTurning']?.play()
  $: $actions['FLTireRot']?.play()
  $: $actions['FRTurning']?.play()
  $: $actions['FRTireRot']?.play()
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Empty" position={[-19.97, 0, 30.32]}>
        <T.Mesh
          name="Body"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Body.geometry}
          material={gltf.materials['Farm3.022']}
          position={[-0.03, 1.1, 0.01]}
          rotation={[-3.14, 0, 3.14]}
        >
          <T.Mesh
            name="PerfectChili"
            castShadow
            receiveShadow
            geometry={gltf.nodes.PerfectChili.geometry}
            material={gltf.materials['Perfect_Baked.003']}
            position={[0.01, 0.21, -0.77]}
            rotation={[-3.14, 0, 3.14]}
          />
        </T.Mesh>
        <T.Mesh
          name="Tire_tireBL"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Tire_tireBL.geometry}
          material={gltf.materials['Farm3.022']}
          position={[-0.77, 0.81, 1.16]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <T.Mesh
          name="Tire_tireBR"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Tire_tireBR.geometry}
          material={gltf.materials['Farm3.022']}
          position={[0.74, 0.81, 1.15]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <T.Mesh
          name="Tire_tireFL"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Tire_tireFL.geometry}
          material={gltf.materials['Farm3.022']}
          position={[-0.49, 0.43, -0.93]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <T.Mesh
          name="Tire_tireFR"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Tire_tireFR.geometry}
          material={gltf.materials['Farm3.022']}
          position={[0.48, 0.43, -0.93]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
