<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 garage.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/garage-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.SM_Bld_Garage_01001.geometry}
      material={gltf.materials.Farm3}
      position={[-20, -0.3, 36]}
      rotation={[Math.PI, 0, Math.PI]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Garage_01_Door001.geometry}
        material={gltf.materials.Farm3}
      />
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
