<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 outhouse.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/outhouse-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.SM_Bld_Outhouse_01001.geometry}
      material={gltf.materials['Farm3.020']}
      position={[-38, 0, 36]}
      rotation={[0, 1.57, 0]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Bld_Outhouse_Door_01001.geometry}
        material={gltf.materials['Farm3.020']}
        position={[-0.5, 1.08, 0.91]}
      />
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
