<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 plant.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/plant-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="ChillingChili_Plant"
        castShadow
        receiveShadow
        geometry={gltf.nodes.ChillingChili_Plant.geometry}
        material={gltf.materials.lambert4SG}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.04}
      >
        <T.Mesh
          name="PerfectChili004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili004.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[42.79, -11.73, 135.98]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={23.81}
        />
        <T.Mesh
          name="PerfectChili005"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili005.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[72.9, -26.13, 131.8]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={23.81}
        />
        <T.Mesh
          name="PerfectChili006"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili006.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-42.44, -22.93, 166.32]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={23.81}
        />
        <T.Mesh
          name="PerfectChili007"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili007.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[33.46, 8.36, 196.02]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={23.81}
        />
        <T.Mesh
          name="PerfectChili008"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili008.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-61.02, -22.93, 164.04]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={12.32}
        />
        <T.Mesh
          name="PerfectChili009"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili009.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-73.16, -29, 157.28]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili010"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili010.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-53.36, -24.57, 165.45]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={17.7}
        />
        <T.Mesh
          name="PerfectChili011"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili011.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-67.6, -24.99, 160.77]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili012"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili012.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-35.33, -18.49, 169.27]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={12.13}
        />
        <T.Mesh
          name="PerfectChili013"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili013.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-23.89, -17.74, 172.2]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={6.48}
        />
        <T.Mesh
          name="PerfectChili014"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili014.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-17.71, -13.79, 170.64]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili015"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili015.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-23.46, -21.31, 170.58]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili016"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili016.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-14.26, -20.37, 170.99]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili017"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili017.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-9.99, -14.21, 172.1]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili018"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili018.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[23.85, -4.01, 146.14]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={16.66}
        />
        <T.Mesh
          name="PerfectChili019"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili019.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-58.19, 27.6, 125.69]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={23.81}
        />
        <T.Mesh
          name="PerfectChili020"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili020.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-68.71, 42.92, 119.77]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={12.32}
        />
        <T.Mesh
          name="PerfectChili021"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili021.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-80.58, 49.49, 117.96]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili022"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili022.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-65.72, 35.67, 122.86]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={17.7}
        />
        <T.Mesh
          name="PerfectChili023"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili023.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-74.13, 47.18, 121.45]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili024"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili024.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-55.08, 21.11, 127.83]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={12.13}
        />
        <T.Mesh
          name="PerfectChili025"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili025.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-47.59, 25.53, 120.52]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={6.48}
        />
        <T.Mesh
          name="PerfectChili026"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili026.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-44.25, 20.82, 121.1]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili027"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili027.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-48.88, 16.9, 127.16]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili028"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili028.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-40.13, 5.82, 124.43]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili029"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili029.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-32.63, 5.79, 126.96]}
          rotation={[-Math.PI / 2, 0.97, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili035"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili035.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[24.6, -29.54, 229.69]}
          rotation={[-Math.PI / 2, 0.9, Math.PI]}
          scale={23.81}
        />
        <T.Mesh
          name="PerfectChili036"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili036.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[22.01, -10.67, 227.06]}
          rotation={[Math.PI / 2, 1.43, 0]}
          scale={12.32}
        />
        <T.Mesh
          name="PerfectChili037"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili037.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[22.93, 1.73, 218.69]}
          rotation={[-Math.PI / 2, 0.62, Math.PI]}
          scale={7.99}
        />
        <T.Mesh
          name="PerfectChili038"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili038.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[23.51, -18.2, 228.82]}
          rotation={[-Math.PI / 2, -0.39, -Math.PI]}
          scale={17.7}
        />
        <T.Mesh
          name="PerfectChili039"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili039.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[22.95, -5.41, 224.14]}
          rotation={[-Math.PI / 2, 0.82, Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili040"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili040.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[27.99, -37.2, 232.64]}
          rotation={[-Math.PI / 2, 0.29, -Math.PI]}
          scale={12.13}
        />
        <T.Mesh
          name="PerfectChili041"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili041.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[24.43, -49.24, 238.18]}
          rotation={[-Math.PI / 2, -0.54, Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili042"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili042.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[15.87, -48.76, 226.73]}
          rotation={[Math.PI / 2, 1.27, 0]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili043"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili043.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[25.06, -63.58, 233.98]}
          rotation={[Math.PI / 2, -1, 0]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili044"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili044.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[34.23, -56.3, 235.48]}
          rotation={[-Math.PI / 2, 1.37, -Math.PI]}
          scale={11.62}
        />
        <T.Mesh
          name="PerfectChili045"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili045.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[44.14, 20.69, 200.74]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={6.9}
        />
        <T.Mesh
          name="PerfectChili046"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili046.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-42.35, 39.29, 209.44]}
          rotation={[-Math.PI / 2, 0.41, Math.PI]}
          scale={10}
        />
        <T.Mesh
          name="PerfectChili048"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili048.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-51.31, 47.38, 213.39]}
          rotation={[-Math.PI / 2, 0.12, -Math.PI]}
          scale={4.88}
        />
        <T.Mesh
          name="PerfectChili049"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili049.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-62.13, 68.67, 201.16]}
          rotation={[-Math.PI / 2, 1.12, -Math.PI]}
          scale={5.52}
        />
        <T.Mesh
          name="PerfectChili050"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili050.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-54.52, 54.95, 210.28]}
          rotation={[-Math.PI / 2, 0.33, -Math.PI]}
          scale={4.88}
        />
        <T.Mesh
          name="PerfectChili052"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili052.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-40.57, 28.06, 213.85]}
          rotation={[-Math.PI / 2, -1.04, -Math.PI]}
          scale={4.88}
        />
        <T.Mesh
          name="PerfectChili054"
          castShadow
          receiveShadow
          geometry={gltf.nodes.PerfectChili054.geometry}
          material={gltf.materials['Perfect_Baked.004']}
          position={[-37.32, 23.78, 213.32]}
          rotation={[Math.PI / 2, -0.73, 0]}
          scale={4.88}
        />
      </T.Mesh>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
