<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 walkingchili.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/walkingchili-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions['WheelBarrow']?.play()
  $: $actions['WheelBarrowWalk']?.play()
  $: $actions['WheelBarrowWheel']?.play()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="WheelBarrow">
      <T.Group name="Empty001" position={[-26.53, 0, -0.23]} rotation={[0, 0.04, 0]}>
        <T.Group name="Mixamo_RIG001">
          <T is={gltf.nodes.mixamorigHips_1} />
          <T.SkinnedMesh
            name="PerfectChili031"
            castShadow
            receiveShadow
            geometry={gltf.nodes.PerfectChili031.geometry}
            material={gltf.materials['Perfect_Baked.005']}
            skeleton={gltf.nodes.PerfectChili031.skeleton}
            morphTargetDictionary={gltf.nodes.PerfectChili031.morphTargetDictionary}
            morphTargetInfluences={gltf.nodes.PerfectChili031.morphTargetInfluences}
          />
        </T.Group>
        <T.Mesh
          name="wheel"
          castShadow
          receiveShadow
          geometry={gltf.nodes.wheel.geometry}
          material={gltf.materials['Farm3.041']}
          position={[0.01, 0.15, 1.02]}
          rotation={[0, 1.57, 0]}
          scale={0.6}
        />
        <T.Mesh
          name="barrow"
          castShadow
          receiveShadow
          geometry={gltf.nodes.barrow.geometry}
          material={gltf.materials['Farm3.041']}
          position={[0.01, 0.15, 1.02]}
          rotation={[0.13, Math.PI / 2, 0]}
          scale={[0.6, 0.6, 0.87]}
        />
        <T.Group
          name="BitCoin_LowPoly_FFC107_0001"
          position={[0, 0.41, 0.75]}
          rotation={[-0.29, -0.04, -0.01]}
          scale={0}
        >
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0002" position={[0, 0.43, 0.71]} rotation={[-0.29, 0.03, 0.01]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0003" position={[0, 0.44, 0.67]} rotation={[-0.29, 0.09, 0.03]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0004" position={[0, 0.39, 0.79]} rotation={[-0.29, 0.1, 0.03]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0005" position={[0, 0.46, 0.62]} rotation={[-0.29, 0, 0]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0006" position={[0, 0.45, 0.54]} rotation={[-0.59, 0, 0]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0007" position={[0, 0.45, 0.46]} rotation={[-0.78, 0, 0]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
        <T.Group name="BitCoin_LowPoly_FFC107_0008" position={[0, 0.44, 0.37]} rotation={[-1.03, 0, 0]} scale={0}>
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0.geometry}
            material={gltf.materials.FFC107}
          />
          <T.Mesh
            name="BitCoin_LowPoly_FFC107_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.BitCoin_LowPoly_FFC107_0_1.geometry}
            material={gltf.materials.FFFFFF}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
