<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 windmill.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/windmill-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions['Blade']?.play()
  $: $actions['Yaw']?.play()
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="SM_Prop_Windmill_01001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SM_Prop_Windmill_01001.geometry}
        material={gltf.materials['Farm3.001']}
        position={[-26.54, 0, -31.4]}
      >
        <T.Mesh
          name="SM_Prop_Windmill_Top_01001"
          castShadow
          receiveShadow
          geometry={gltf.nodes.SM_Prop_Windmill_Top_01001.geometry}
          material={gltf.materials['Farm3.001']}
        >
          <T.Mesh
            name="SM_Prop_Windmill_Blades_01001"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SM_Prop_Windmill_Blades_01001.geometry}
            material={gltf.materials['Farm3.001']}
            position={[-0.03, 9.54, 1.01]}
          />
        </T.Mesh>
      </T.Mesh>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
