<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 signpost.glb -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/signpost-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.SIGN.geometry} material={gltf.materials.SignPost}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_about001'].geometry}
        material={gltf.materials.SignPost}
        position={[0.08, 2.62, -0.07]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['2_token001'].geometry}
        material={gltf.materials.SignPost}
        position={[-0.02, 2.16, -0.1]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['3_utility001'].geometry}
        material={gltf.materials.SignPost}
        position={[-0.01, 1.67, -0.08]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['4_faq001'].geometry}
        material={gltf.materials.SignPost}
        position={[0.03, 1.19, -0.07]}
      />
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
